version: '3.8'

services:

  db:
    image: postgres:15
    container_name: smm-db
    environment:
      POSTGRES_USER: smm-user
      POSTGRES_PASSWORD: smm-password
      POSTGRES_DB: smm-db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smm-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://smm-user:smm-password@db:5432/smm-db
      GEMINI_API_KEY: AIzaSyDGofR29HIq3sDsvXAo6Abl5ziLIhalOII
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads   # persist uploaded files

  frontend:
    build: ./frontend
    container_name: smm-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: